[galaxias]
banda = "MIPS70"
archivo_sufijo = "_mips70_image_v5-0.fits"
galaxias = [
    "ddo154",
    "ddo165",
    "hoii",
    "ic2574",
    "ic4710",
    "mrk33",
    "ngc0024",
    "ngc0337",
    "ngc0584",
    "ngc0628",
    "ngc0925",
    "ngc1097",
    "ngc1266",
    "ngc1291",
    "ngc1316",
    "ngc1377",
    "ngc1404",
    "ngc1482",
    "ngc1512",
    "ngc1566",
    "ngc1705",
    "ngc2798",
    "ngc2841",
    "ngc2976",
    "ngc3031",
    "ngc3034",
    "ngc3049",
    "ngc3184",
    "ngc3190",
    "ngc3198",
    "ngc3265",
    "ngc3621",
    "ngc4594",
    "ngc5194",
]
